from setuptools import setup, find_packages
import os

moduleDirectory = os.path.dirname(os.path.realpath(__file__))
exec(open(moduleDirectory + "/marshall_webapp/__version__.py").read())

def readme():
    with open(moduleDirectory + '/README.md') as f:
        return f.read()

install_requires = [
    'pyyaml',
    'marshall_webapp',
    'fundamentals',
    'pyramid',
    'pyramid_chameleon',
    'pyramid_debugtoolbar',
    'waitress',
    'paste',
    'sqlalchemy',
    'mod_wsgi',
    'khufu',
    'dryxPyramid',
    'pymysql',
    'astrocalc',
    'psutil',
    'unicodecsv',
    'multiprocess',
    'nose2',
    'marshallEngine',
    'webtest'
]

# READ THE DOCS SERVERS
exists = os.path.exists("/home/docs/")
if exists:
    c_exclude_list = ['healpy', 'astropy',
                      'numpy', 'sherlock', 'wcsaxes', 'HMpTy', 'ligo-gracedb']
    for e in c_exclude_list:
        try:
            install_requires.remove(e)
        except:
            pass

setup(name="marshall_webapp",
      version=__version__,
      description="Astronomical-transient marshalling webapp for curating and managing streams of object observations generated by wide-field surveys",
      long_description=readme(),
      long_description_content_type='text/markdown',
      classifiers=[
          'Development Status :: 4 - Beta',
          'License :: OSI Approved :: MIT License',
          'Programming Language :: Python :: 3.7',
          'Programming Language :: Python :: 2.7',
          'Topic :: Utilities',
      ],
      keywords=['astronomy, marshall, webapp'],
      url='https://github.com/thespacedoctor/marshall_webapp',
      download_url='https://github.com/thespacedoctor/marshall_webapp/archive/v%(__version__)s.zip' % locals(
      ),
      author='David Young',
      author_email='davidrobertyoung@gmail.com',
      license='MIT',
      packages=find_packages(),
      include_package_data=True,
      install_requires=install_requires,
      test_suite='nose2.collector.collector',
      tests_require=['nose2', 'cov-core'],
      entry_points={
          'paste.app_factory': ['main=marshall_webapp:main', ],
          'console_scripts': ['marshall_webapp=marshall_webapp.cl_utils:main'],
      },
      zip_safe=False)
