from templates_transients import templates_transients
from templates_stats import templates_stats
from templates_calendars import templates_calendars
from templates_transient_comments import templates_transient_comments
from templates_transientLightcurves import templates_transientLightcurves

from templates_transients_ob import templates_transients_ob

