from templates_transients import templates_transients
from templates_stats import templates_stats
from templates_calendars import templates_calendars

from templates_transientComments import templates_transientComments
from templates_transientLightcurves import templates_transientLightcurves
