#!/usr/bin/env bash

# ['/home/marshall/.virtualenv/marshall_webapp/bin/mod_wsgi-express', 'setup-server', 'production_qubvm.wsgi', '--port=8090', '--user', 'marshall', '--group', 'marshall', '--server-root=/misc/pessto/git_repos/marshall_webapp/apache']

HTTPD="/usr/sbin/httpd -f /misc/pessto/git_repos/marshall_webapp/apache/httpd.conf "

SHLIBPATH=""

if [ "x$SHLIBPATH" != "x" ]; then
    LD_LIBRARY_PATH="$SHLIBPATH:$LD_LIBRARY_PATH"
    export LD_LIBRARY_PATH
fi

WSGI_RUN_USER="${WSGI_RUN_USER:-marshall}"
WSGI_RUN_GROUP="${WSGI_RUN_GROUP:-marshall}"

export WSGI_RUN_USER
export WSGI_RUN_GROUP

if [ `id -u` = "0" -a ${WSGI_RUN_USER} = "root" ]; then
    cat << EOF

WARNING: When running as the 'root' user, it is required that the options
'--user' and '--group' be specified to mod_wsgi-express. These should
define a non 'root' user and group under which the Apache child worker
processes and mod_wsgi daemon processes should be run. Failure to specify
these options will result in Apache and/or the mod_wsgi daemon processes
failing to start. See the mod_wsgi-express documentation for further
information on this restriction.

EOF

fi

LANG='en_GB.UTF-8'
LC_ALL='en_GB.UTF-8'

export LANG
export LC_ALL

ACMD="$1"
ARGV="$@"

if test -f /misc/pessto/git_repos/marshall_webapp/apache/envvars; then
    . /misc/pessto/git_repos/marshall_webapp/apache/envvars
fi

STATUSURL="http://localhost:8090/server-status"

if [ "x$ARGV" = "x" ]; then
    ARGV="-h"
fi

PROCESS_NAME="httpd (mod_wsgi-express) "

case $ACMD in
start|stop|restart|graceful|graceful-stop)
    exec -a "$PROCESS_NAME" $HTTPD -k $ARGV
    ;;
configtest)
    exec $HTTPD -t
    ;;
status)
    exec /home/marshall/.virtualenv/marshall_webapp/bin/python -m webbrowser -t $STATUSURL
    ;;
*)
    exec $HTTPD $ARGV
esac

