#!/usr/bin/env bash

# ['/home/marshall/.virtualenv/marshall_webapp/bin/mod_wsgi-express', 'setup-server', 'production_qubvm.wsgi', '--port=8090', '--user', 'marshall', '--group', 'marshall', '--server-root=/misc/pessto/git_repos/marshall_webapp/apache']

HTTPD="/usr/sbin/httpd"
HTTPD_ARGS="-f /misc/pessto/git_repos/marshall_webapp/apache/httpd.conf "

HTTPD_COMMAND="$HTTPD $HTTPD_ARGS"

MOD_WSGI_MODULES_DIRECTORY="/usr/lib64/httpd/modules"
export MOD_WSGI_MODULES_DIRECTORY

SHLIBPATH=""

if [ "x$SHLIBPATH" != "x" ]; then
    LD_LIBRARY_PATH="$SHLIBPATH:$LD_LIBRARY_PATH"
    export LD_LIBRARY_PATH
fi

MOD_WSGI_SERVER_ROOT="/misc/pessto/git_repos/marshall_webapp/apache"

export MOD_WSGI_SERVER_ROOT

MOD_WSGI_LISTENER_HOST="localhost"

export MOD_WSGI_LISTENER_HOST

MOD_WSGI_HTTP_PORT="8090"
MOD_WSGI_HTTPS_PORT="None"

export MOD_WSGI_HTTP_PORT
export MOD_WSGI_HTTPS_PORT

MOD_WSGI_USER="${MOD_WSGI_USER:-marshall}"
MOD_WSGI_GROUP="${MOD_WSGI_GROUP:-marshall}"

export MOD_WSGI_USER
export MOD_WSGI_GROUP

if [ `id -u` = "0" -a ${MOD_WSGI_USER} = "root" ]; then
    cat << EOF

WARNING: When running as the 'root' user, it is required that the options
'--user' and '--group' be specified to mod_wsgi-express. These should
define a non 'root' user and group under which the Apache child worker
processes and mod_wsgi daemon processes should be run. Failure to specify
these options will result in Apache and/or the mod_wsgi daemon processes
failing to start. See the mod_wsgi-express documentation for further
information on this restriction.

EOF

fi

MOD_WSGI_WORKING_DIRECTORY="/misc/pessto/git_repos/marshall_webapp"

export MOD_WSGI_WORKING_DIRECTORY

LANG='en_GB.UTF-8'
LC_ALL='en_GB.UTF-8'

export LANG
export LC_ALL

ACMD="$1"
ARGV="$@"

if test -f /misc/pessto/git_repos/marshall_webapp/apache/envvars; then
    . /misc/pessto/git_repos/marshall_webapp/apache/envvars
fi

STATUSURL="http://localhost:8090/server-status"

if [ "x$ARGV" = "x" ]; then
    ARGV="-h"
fi

GDB="gdb"
ENABLE_GDB="False"

PROCESS_NAME="httpd (mod_wsgi-express) "

case $ACMD in
start|stop|restart|graceful|graceful-stop)
    if [ "x$ENABLE_GDB" != "xTrue" ]; then
        exec -a "$PROCESS_NAME" $HTTPD_COMMAND -k $ARGV
    else
        echo "run $HTTPD_ARGS -k $ARGV" > /misc/pessto/git_repos/marshall_webapp/apache/gdb.cmds
        gdb -x /misc/pessto/git_repos/marshall_webapp/apache/gdb.cmds $HTTPD
    fi
    ;;
configtest)
    exec $HTTPD_COMMAND -t
    ;;
status)
    exec /home/marshall/.virtualenv/marshall_webapp/bin/python -m webbrowser -t $STATUSURL
    ;;
*)
    exec $HTTPD_COMMAND $ARGV
esac

