version: 1

# THESE ADVANCED SETTINGS ARE COLLECTED WHEN USING CL-TOOLS, 
# BUT IF PACKAGE IS TO BE IMPORTED WITHIN OTHER CODE YOU NEED TO INCLUDE THIS PYTHON SNIPPET
# WHERE NEEDED IN THIS PACKAGE
# xt-collect-packages-advanced-settings
